.\" t
.de TQ
.  br
.  ns
.  TP \\$1
..
.TH CAMOTO-STUDIO "1" "May 2011" "Camoto" "User Commands"
.SH NAME
camoto-studio \- core GUI interface to most Camoto functionality
.SH SYNOPSIS
.B camoto-studio [\fI-action file\fR]
.SH DESCRIPTION
.PP
Open the GUI, optionally performing the given action.
.SH ACTIONS
.TP
\fB-project\fR
open the given project file.  Pass the full path and filename of
\'project.camoto\', located inside the project folder.
.TP
\fB-music\fR
open the given music file in a standalone editor
.SH AUTHOR
Written by Adam Nielsen <malvineous@shikadi.net>.
.SH "REPORTING BUGS"
Report bugs to <camoto@lists.shikadi.net>.
.SH COPYRIGHT
Copyright \(co 2010-2011 Adam Nielsen.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
\fBgamearch\fR(1), \fBgamecomp\fR(1), \fBgamegfx\fR(1), \fBgamemap\fR(1),
\fBgamemus\fR(1), <http://www.shikadi.net/camoto>
.PP
All the games and file formats supported by Camoto are fully documented
on the Game Modding Wiki \fB<http://www.shikadi.net/moddingwiki>\fR.
.PP
This utility is part of the Camoto suite of tools.
